on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: purescript-contrib/setup-purescript@v3.1.0
      with:
        spago: "latest"
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-spago-${{ hashFiles('**/spago*') }}
        path: |
          spago.lock
          .spago
          output
          examples/*/dist
    - run: spago build
    - run: build-examples.sh

    # Is this necessary?
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./dist
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
